### PR TITLE
Update emigration.md

### PR DESCRIPTION
**Pull request by rlskoeser**
Opening PR on behalf of @jhimpele 

> Moving to a different branch. Unclear if this is a "removal" strictly  defined. If there is room on the Lands + Waters, we might move it here until there is more detail.

### CODE REVIEW

**Comment by rlskoeser** [comment]
@jhimpele I didn't see a PR but saw your change in a branch, so I opened a PR for you. You can see how it looks on the render site - the leaf is being placed pretty far from the 1600s band. Looking at this branch now, I'm wondering if the x axis force (for branch) and perhaps network forced layout are overpowering the y axis century force...

**Comment by rlskoeser** [comment]
@jhimpele different question:
> Moving to a different branch. Unclear if this is a "removal" strictly  defined. If there is room on the Lands + Waters, we might move it here until there is more detail.

How do you define removal? Do you mean forced removal?

**Comment by jhimpele** [comment]
Thanks for that. I committed but may have forgotten the pull request.

At any rate, I see where it also pushes other leaves off of the graph. Let’s do this, would you move it back to removals until we learn more? It’s possible we’ll be “removing” it completely, but I will need to dig into Izzy’s work to where the data came from…

From: Rebecca Sutton Koeser ***@***.***>
Date: Friday, August 25, 2023 at 3:54 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Update emigration.md (PR #260)

@jhimpele<https://github.com/jhimpele> I didn't see a PR but saw your change in a branch, so I opened a PR for you. You can see how it looks on the render site - the leaf is being placed pretty far from the 1600s band. Looking at this branch now, I'm wondering if the x axis force (for branch) and perhaps network forced layout are overpowering the y axis century force...

**Comment by jhimpele** [comment]
Exactly. There was later an official US Removal policy, but here we are using the term to migrations also forced by deception, violence or dispossession.



From: Rebecca Sutton Koeser ***@***.***>
Date: Friday, August 25, 2023 at 3:55 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Update emigration.md (PR #260)

@jhimpele<https://github.com/jhimpele> different question:

Moving to a different branch. Unclear if this is a "removal" strictly defined. If there is room on the Lands + Waters, we might move it here until there is more detail.

How do you define removal? Do you mean forced removal?

**Pull request closed without merging**
