### PR TITLE
Implement leaf states; trigger hover state for both leaf/label when either is hovered

### PR DESCRIPTION
**Pull request by rlskoeser**
implements leaf states per #92 

## notes
- I've implemented the disabled style (including disabling pointer events), but the only way to see it is if you inspect and manually set a `disabled` class on a leaf path element.
- implemented focus color outline as documented; easy to revise the color in one place if/when you change to black
- I used the shadow radius exactly as you had it in Figma; please check that it displays the way you expect/want. (I wondered if maybe the sizing is wrong because we adjusted the size of the leaves, and I'm not sure if you adjusted them in Figma)

additional functionality: since in the current layout it is not always obvious which leaf and label correspond, I added logic to trigger hover state for corresponding leaf/label when the other one is hovered and wrote a new user story #92 

I'm setting labels to bold on hover/active because they aren't visible enough to me without this. @gissoo I remember we discussed and I think you didn't want to do this but I don't remember if you were working on an alternative.

still to do: I would like to write js unit tests for the new functionality, but would be easier to merge #96 first

### CODE REVIEW

**Comment by gissoo** [comment]
@rlskoeser thank you!! 

- the glow function's colors are not correct, they look like they have a lot of white in them, I can't seem to find where the problem is but none of them match the glow colors. 
- the glow function is not working on my safari (even though it's been updated!)
- the size of the glow isn't right as you mentioned. It will be a lot easier for me to change them in the code locally. I can do it this week!

**Comment by rlskoeser** [comment]
@gissoo here are the relevant files for you to adjust colors and size of the glow. All the scss files are under `themes/timetree/assets`.
- colors are all defined in [scss/base/_colors.scss](https://github.com/Princeton-CDH/lenape-timetree/blob/feature/leaf-states/themes/timetree/assets/scss/base/_colors.scss#L39-L51)
- mixin for leaf states; takes a parameter for branch to select correct set of colors [scss/pages/_timetree.scss](https://github.com/Princeton-CDH/lenape-timetree/blob/feature/leaf-states/themes/timetree/assets/scss/pages/_timetree.scss#L74-L105)

(the links will take you to specific lines that are most relevant)

I think I copied the colors correctly from Figma, but please confirm. You'll see I have commented out `rgba` versions of the colors, which were available in the Figma styles; I can't remember why I didn't use those. Could be useful to play with the rgba versions and the opacity.

I wonder if the browsers automatically decrease the opacity for the color used to generate the glow / shadow? 

Not sure what's going on with Safari, I would guess it doesn't properly support the css filter we have to use with SVG path elements. I found [an issue](https://github.com/mdn/browser-compat-data/issues/17726) suggesting problems with filter + drop-shadow on Safari, but IDK if this is exactly our problem.

**Comment by rlskoeser** [comment]
@gissoo thank you for confirming. Can we identify a minimal adjustment to the glow styles so we can get this version merged in? We can always add an issue to fine tune the styles further.

**Comment by gissoo** [comment]
@rlskoeser thank you – can you merge as is and I can suggest changes next week? 

I'd really prefer to see the tweaks I'm making in the browser and I can't find the lines you're linking to here locally yet so that I can change them, is it because it's not merged yet? I copied all the new code to my local setup to see the glow effect in the browser first but I think I'm not calling the get-map somewhere, it's not successful.

**Comment by rlskoeser** [comment]
@gissoo oh, sorry! if you want to make changes to this version of the code you have to check out this branch (`feature/leaf-states`).  Merging it might be easier, then you can suggest a change based on the code in develop and I can review.

If you have a number and want me to make an initial adjustment the scale/size of the glow, LMK — can tweak before I merge.

**Pull request merged**
