### PR TITLE
Feature/zoom

### PR DESCRIPTION
**Pull request by rlskoeser**
this is branched from the multiline label work, implementing basic d3 zoom logic as a starting point so that we can refine

### CODE REVIEW

**Comment by gissoo** [comment]
@rlskoeser is this meant to be reviewed on mobile only? 
- I was envisioning that when you zoom on desktop it will zoom within the limits of the svg container – do we prefer this?
Screenshot 2023-02-13 at 4 12 28 PM

- If we decide it will look like the above screenshot then I think we should hide the footer when the zoom is active. 

- I do expect something like the above screenshot happening on zoom on mobile

**Comment by rlskoeser** [comment]
> is this meant to be reviewed on mobile only? 

Should there be any zoom on desktop, or is it only for mobile? 

> I was envisioning that when you zoom on desktop it will zoom within the limits of the svg container – do we prefer this?

No, sorry! I thought I added a style change to hide overflow, which should truncate at the boundary of the svg container, but maybe I didn't push that change.

**Comment by gissoo** [comment]
> > is this meant to be reviewed on mobile only?
> 
> Should there be any zoom on desktop, or is it only for mobile?

@rlskoeser I think we'll need it on desktop, as I mentioned I don't think we should try to show everything at once on desktop. 

> 
> > I was envisioning that when you zoom on desktop it will zoom within the limits of the svg container – do we prefer this?
> 
> No, sorry! I thought I added a style change to hide overflow, which should truncate at the boundary of the svg container, but maybe I didn't push that change.

- ah that makes sense, thanks

**Comment by rlskoeser** [comment]
closing this PR since we're not ready to implement zoom

**Pull request closed without merging**
