### PR TITLE
Revise panel styles, implement close button and branch leaf icon

### PR DESCRIPTION
**Pull request by rlskoeser**
includes several design updates and implementations:
- panel resizing as determined in co-working meeting today
- new colors for header, footer, and panel, as well as box-shadow style per #125 
- implement close button with phosphor icon and placement/sizing per #84 
- implement leaf label icon for branch in leaf details #119 

Also includes some updates to organize timetree scss a bit (new component for the panel), some name changes so styles/logic is more semantic and readable, and html change to make the close button more accessible. Revised the content positioning and flow for showing/hiding the panel and shrinking/expanding to fit content (using flexbox + columns); I have a placeholder for where the active label will be added.  I also added the Phosphor info icon image and style while I was adding the x button, so it will be ready to use when we get to #85

## design review
@gissoo please check the styles - hopefully useful to review on percy as well as the render site
- [x] updated colors for header, footer, panel
- [x] close button icon, sizing, placement
- [x] branch leaf label icon - sizing, placement, colors
- [x] panel sizing and content flow (adjusts size based on content; scrollable when appropriate; fixed to top of container on desktop and bottom on mobile)

## revisions
- [x] max height for panel on desktop
- [x] x and leaf icons cut off in chrome
- [x] firefox max-height weirdness

### CODE REVIEW

**Comment by gissoo** [comment]
@rlskoeser thank you!! Everything looks and works great!! Can we define a max height for the panel on desktop?
The only requirement I have in mind is about a 27px gap between the bottom of the panel and the top of the footer so the situation below wouldn't happen. 
Screenshot 2023-03-29 at 1 43 16 PM

**Comment by gissoo** [comment]
@rlskoeser thank you for the revisions!! Sure, we can talk about the problem on firefox in person.
The following have been fixed:
- the close button and the leaf inside the panel aren't getting cut off anymore on Chrome
- the height of the panel on desktop is great, there are no more overlaps with the footer

There are a few problems:
- on chrome mobile simulator now the long panels are covering the whole screen and are not scrolling (like the #sand-hill leaf) 
- the project description panel appears a bit higher than the leaf panels (so when you choose your first leaf there is a shift, which is a bit annoying)

**Comment by gissoo** [comment]
@rlskoeser I resolved the issue with the height of the page on firefox, something was messed up in my browser's emulator settings. Thank you for pointing it out! It looks fine on Firefox

**Comment by rlskoeser** [comment]
> @rlskoeser I resolved the issue with the height of the page on firefox, something was messed up in my browser's emulator settings. Thank you for pointing it out! It looks fine on Firefox

@gissoo whew, thanks for confirming! 

@gissoo I made enough changes that I would prefer you test my latest revisions before we merge.  I had to rework the styles a bit to address the problem you found (I switched from flex to grid because I couldn't get the zero-height item to not take up any space in the flex column). There are some interesting constraints with the different sizing options; limiting the overflow vertically without hiding the box-shadow on desktop is kind of tricky!

**Comment by gissoo** [comment]
@rlskoeser thanks for the changes. So it looks like now the panels that are too short have more space at their bottom than we originally intended, this is because you switched to grid? (They look ok) 
- the transition between devices looks good! 
- a link in #chief-mark-peters is not wrapped so the panel is scrolling horizontally – 
- the position of the project description/leaf panel is fixed now, so there is no more jumping between them
- on safari there is a jump in the position of the tree, when some leaves are active the tree sits higher and with other it sits lower. (e.g. on #exodus it sits higher then on #midwest-resettlement it goes down a lot)

**Comment by rlskoeser** [comment]
Fixed the overflow wrapping for chrome; not sure what's going on with safari (container size changing, maybe?), and it looks like the max length doesn't always work in safari either (but sometimes does?!). But we'll track that on a separate issue so we can get those changes merged.

**Pull request merged**
