### PR TITLE
Implement desktop and mobile type styles

### PR DESCRIPTION
**Pull request by rlskoeser**
ref #47 

in this PR:
- add Overlock font files
- add type styles to css
- adjust leaf details content / layout to match designs
- add indicator in footer nav when homepage is the current page

revisions needed:
- [x] remove -1 letter spacing
- [x] check font display in Safari browser

### CODE REVIEW

**Comment by gissoo** [comment]
@rlskoeser thank you so much for these!! They look great. Looking again after sometime is really helpful, realizing the letter spacing is too tight, could we revise everything from -1px to 0? Other than that everything looks good!

**Comment by gissoo** [comment]
@rlskoeser for some reason on Percy when viewing the screenshots from different browsers none of them seem to be displaying the correct font, do you know why that is?

**Comment by rlskoeser** [comment]
> @rlskoeser for some reason on Percy when viewing the screenshots from different browsers none of them seem to be displaying the correct font, do you know why that is?

I just looked — it looks to me like all the browsers except Safari are displaying the font properly. Is that what you're seeing? Or am I missing something?

I can look into the Safari issue, thanks for flagging.

**Comment by rlskoeser** [comment]
FYI, the fallback font in Google's CSS for Overlock was `cursive`; please LMK if you prefer something different.

**Comment by gissoo** [comment]
@rlskoeser I only checked them on Percy and noticed the issue there. It might be a different problem then on Percy's side. 
Glad they are ok in your tests. 

I'm not able to find a good option right now for the fallback, it's on my list now, will let you know soon.

**Review by gissoo — APPROVED** [review]

**Comment by rlskoeser** [comment]
@gissoo can you share specifics and/or a link to the Percy views you're looking at so I can check what you're seeing? I think I should fix it before we merge this.

But glad that otherwise the type styles look good! It should be easy to drop the -1 letter spacing — do you want to review again once I make the change?

**Comment by rlskoeser** [comment]
@gissoo I've removed the -1 letter spacing. Do you want to look before we merge?

I checked with my version of Safari locally and the fonts render normally. I vaguely recall we had a problem with Safari in Percy before and they were using an older version, which makes it hard to troubleshoot. I tried one small change but it didn't help. Should I turn off Safari rendering? It would be good to test, but if we can't get the correct fonts to load it seems pretty useless.

**Comment by gissoo** [comment]
@rlskoeser thank you, the letter spacing looks a lot better now!! 
- I'm not sure about your question on Safari since all four browsers on Percy aren't showing me the right font in the screenshots

**Comment by gissoo** [comment]
Let's not turn Safari off, we'll have more designs to test, it's worth seeing how other parts of the site look like on Safari in the future

**Pull request merged**
